
cd /Users/edwardarubin/Dropbox/Teaching/ARE212

Rscript -e 'rmarkdown::render_site("contact.Rmd")'
Rscript -e 'rmarkdown::render_site("courseInfo.Rmd")'
Rscript -e 'rmarkdown::render_site("index.Rmd")'
Rscript -e 'rmarkdown::render_site("latexKnitr.Rmd")'
Rscript -e 'rmarkdown::render_site("notes.Rmd")'

Rscript -e 'rmarkdown::render_site("section00.Rmd")'
Rscript -e 'rmarkdown::render_site("section01.Rmd")'
Rscript -e 'rmarkdown::render_site("section02.Rmd")'
Rscript -e 'rmarkdown::render_site("section03.Rmd")'
Rscript -e 'rmarkdown::render_site("section04.Rmd")'
Rscript -e 'rmarkdown::render_site("section05.Rmd")'
Rscript -e 'rmarkdown::render_site("section06.Rmd")'
Rscript -e 'rmarkdown::render_site("section07.Rmd")'
Rscript -e 'rmarkdown::render_site("section08.Rmd")'
Rscript -e 'rmarkdown::render_site("section09.Rmd")'
Rscript -e 'rmarkdown::render_site("section10.Rmd")'
# Rscript -e 'rmarkdown::render_site("section11.Rmd")'
# Rscript -e 'rmarkdown::render_site("section12.Rmd")'
# Rscript -e 'rmarkdown::render_site("section12b.Rmd")'
# Rscript -e 'rmarkdown::render_site("section13.Rmd")'
Rscript -e 'rmarkdown::render_site("syllabi.Rmd")'
